config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'order_complete' => 'cart#order_complete'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

	root 'storefront#all_items'
	get 'categorical/:category_id' => 'storefront#items_by_category', as: 'categorical'
	get 'branding/:brand' => 'storefront#items_by_brand', as: 'branding'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
  	line_item = LineItem.new(product_id: params[:product_id], quantity: params[:quantity])
    line_item.total = line_item.product.price * line_item.quantity
    line_item.save

    redirect_back(fallback_location: root_path)
  end

  def view_order
  	@line_items = LineItem.where(order_id: nil)
  end

  def checkout
    line_items = LineItem.where(order_id: nil)
    @order = Order.create(user_id: current_user.id, subtotal: 0)

    line_items.each do |line_item|
      line_item.product.quantity -= line_item.quantity
      line_item.product.save

      line_item.update(order_id: @order.id)
      @order.subtotal += line_item.total
    end

    @order.sales_tax = @order.subtotal * 0.0825
    @order.grand_total = @order.subtotal + @order.sales_tax

    @order.save
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Thanks for Shopping With Us!</h1>
<p>Let's review your order:</p>


<ul>
<% @order.line_items.each do |line_item| %>
	<li><%= line_item.product.name %></li>
	<li>Qty: <%= line_item.quantity %></li>
<% end %>
</ul>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %> 
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %> 
</p>

<p>
  <strong>Order Total: </strong><%= number_to_currency @order.grand_total %> 
</p>

<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>
  Order #<%= @order.id %> will be shipping to you, 
  <%= @order.user.email %>, as soon as possible!
</p>

app/views/cart/view_order.html.erb
<h2>My Cart</h2>

<div>
  <% @line_items.each do |line_item| %>
    <div class="well row">
      <div class="col-md-2">
	      <% if line_item.product.image.url.nil? == false %>
	        <p><%= image_tag line_item.product.image.url, class: "storefront-pics" %></p>
	      <% end %>
      </div>
      <div class="col-md-10">
		    <p><h4><%= line_item.product.name %></h4></p>
		    <p><%= number_to_currency line_item.product.price %></p>
		    <p>Qty: <%= line_item.quantity %></p>
		    <p>Subtotal: <%= number_to_currency line_item.total %></p> 
		  </div>
		</div>
  <% end %>
</div>

<div>
 <%= link_to "Proceed to Checkout", checkout_path, class: "btn btn-success" %>
</div>