config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'order_complete' => 'cart#order_complete'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

	root 'storefront#all_items'
	get 'categorical/:category_id' => 'storefront#items_by_category', as: 'categorical'
	get 'branding/:brand' => 'storefront#items_by_brand', as: 'branding'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@products = Product.where(category_id: params[:category_id])
  	@category = Category.find(params[:category_id])
  end

  def items_by_brand
  	@products = Product.where(brand: params[:brand])
  	@brand = params[:brand]
  end
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/storefront/_product_loop.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well center-it">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, class: "storefront-pics" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href="#" data-target="#myModal_<%= product.id %>" data-toggle="modal">
            <span class="glyphicon glyphicon-plus"></span> Quick Info
          </a>
        </p>
      </div>
    </div>

    <!-- Modal -->
	<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">
	        	<%= link_to product.name, product %>
	        </h4>
	      </div>
	      <div class="modal-body">
            <% if product.image.url.nil? == false %>
	          <p><%= image_tag product.image.url, class: "storefront-pics" %></p>
	        <% end %>
	        <p><%= number_to_currency product.price %></p>
	        <p>made by <%= product.brand %></p>
		  </div>
	      <div class="modal-footer">
	        <%= form_tag add_to_cart_path do %>
	          <%= hidden_field_tag :product_id, product.id %>
	          <%= number_field_tag :quantity, nil, placeholder: "How many?", class: "form-control" %>
	          <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
 	        <% end %>
	      </div>
	    </div>
	  </div>
	</div>
  <% end %>
</div>

app/views/storefront/all_items.html.erb
<h1>Welcome to Tech Talent Store</h1>
<p>Give us your money!</p>

<%= render 'product_loop' %>

app/views/storefront/items_by_brand.html.erb
<h1><%= @brand %></h1>

<%= render 'product_loop' %>

app/views/storefront/items_by_category.html.erb
<h1><%= @category.name %></h1>

<%= render 'product_loop' %>